inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 100

Metrics/MethodLength: 
  Max: 20

Metrics/AbcSize:
  Max: 30

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false
